name: Update AppLinks
on:
  push:
    branches:
      - 'main'
      - 'web-app'
  workflow_dispatch:

jobs:
  Update-AppLinks:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Merge main and web-app into pages
        run: |
          git fetch origin
          git checkout pages
          git merge origin/main --allow-unrelated-histories -m "Merge main into pages"
          git merge origin/web-app --allow-unrelated-histories -m "Merge web-app into pages"
          git push origin pages