name: Update files
on:
  push:
  workflow_dispatch:

jobs:
  Update-Files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Merge main and web-app
        run: |
          mv web-app/* .
          rm -r web-app
      - name: Update files
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: .
          single-commit: true