name: Update files
on:
  push:
  workflow_dispatch:

jobs:
  Update-Files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository main code
        uses: actions/checkout@v2
      - name: Merge main and web-app
        run: |
          mv web-app/* .
          rm -r web-app
      - name: Update files
        uses: test-room-7/action-update-file@v1
        with:
            file-path: '*'
            commit-msg: Update Files
            github-token: ${{ secrets.GITHUB_TOKEN }}
            branch: pages